BaseParser.js
charCodeAt, not charChodeAt
This only affects systems that use carriage returns (Windows). I'm not sure if/how you'd like to test this as using the autotest format would mean the carriage return (what we're testing) is basically invisible.
=> Fix typo in BaseParser.js

Parser.js, test/autotest-1.x/backtick-string/expected.html, test/autotest/backtick-string-nested-with-space/expected.html, test/autotest/backtick-string-nested-with-space/input.htmljs, test/autotest/backtick-string-placeholder-newline/expected.html, test/autotest/backtick-string-placeholder-newline/input.htmljs, test/autotest/backtick-string/expected.html
The following now parse properly:
```marko
// previously threw an error
<hello message=`${`hi ${name}`}!`></hello>
```
```marko
// previously parsed, but incorrectly included 
// newline escape sequences in the interpolated js
<hello message=`${
foo
}!`></hello>
```
=> template literals:preserve newline literals and parse placeholders

Parser.js, test/autotest/whitespace-only-reset-indent/expected.html, test/autotest/whitespace-only-reset-indent/input.htmljs
reset indent on new-line (to fix whitespace body issue).
fix for 
https://github.com/marko-js/htmljs-parser/issues/63
=> reset indent on new-line

Parser.js, test/autotest-1.x/comment-concise-js-line/expected.html, test/autotest/comment-concise-js-line/expected.html, test/autotest/scriptlet-block-multiline-comment/expected.html, test/autotest/scriptlet-block-single-line-comment/expected.html, test/autotest/scriptlet-line-multiline-comments/expected.html, test/autotest/scriptlet-line-multiline-comments/input.htmljs, test/autotest/scriptlet-line-trailing-line-comment/expected.html, test/autotest/scriptlet-line-trailing-line-comment/input.htmljs, test/autotest/text-after-semicolon/expected.html
Fixes two issues with parsing comments inside scriptlets.
1. Previously an inline script with a trailing single line comment would consume the following two lines because both the inline script and the comment were looking for the end of the line.
This is fixed by making the inline script parsing not include the trailing newline as part of the script.
2. Comments inside inline scripts had an additional `/` which caused multiline comments to not work properly.
This is fixed by not adding the character in a script when we detect we are going into a comment.
=> Fix parsing comments inside of scriptlets

Parser.js, test/autotest/tag-var-declaration/expected.html
Fixes an issue where a tag variable followed by a default attribute was being parsed as a normal attribute without a name instead of having the `default: true` property set.
=> fix: tag var with default attribute properly parsed

Parser.js
For the most part the htmljs-parser supports arbitrary js expressions for all places where a JS expression is allowed. Currently with tag variables, a parenthesis expression cannot be used, eg: `<tag/(x)/>` would error.
This PR supports this, without breaking arguments following a tag var (`<tag/x(y)/>`) which will cause the error to be reported in the Marko compiler itself.
=> fix: support parenthesis within tag var expression

Parser.js, test/autotest-1.x/parsed-text-style-tag-class/expected.html, test/autotest-1.x/parsed-text-style-tag-class/input.htmljs
This PR supports tags parsed in either `static-text` or `parsed-content` mode (such as `<script>` and `<style>`) having a closing tag that matches the same variants as other tags.
Specifically this means the below is newly supported:
```
<style.test></>
<style.test></style>
```
Where as before only `<style.test></style.test>` would have been valid.
=> fix: support closing tag variations on text parse modes

Parser.js, notify-util.js, test/autotest/attr-method-shorthand/expected.html, test/autotest/attr-method-shorthand/input.htmljs
Adds support for parsing shorthand methods as attributes: 
```marko
<foo onclick(event) { 
console.log("hello"); 
event.preventDefault();
}/>
<foo(event) { 
console.log("hello"); 
event.preventDefault();
}/>
```
=> feat: add shorthand method attributes

.github/workflows/ci.yml, .releaserc.json
After merging in the new parser API changes it wasn't setup so that the `main` branch could be released from (only `next`).
This PR fixes that.
=> fix: issues with releasing from main branch

.github/workflows/ci.yml
Fixes an issue where the CI format action was not able to commit formatted files back.
=> chore: allow CI to commit formatted files

.changeset/strong-buckets-attack.md, src/__tests__/fixtures/attr-operators-space-before/__snapshots__/attr-operators-space-before.expected.txt, src/__tests__/fixtures/attr-operators-space-between/__snapshots__/attr-operators-space-between.expected.txt, src/states/EXPRESSION.ts
Fixes a bug where expression continuations containing equals (eg `!=`) were not consuming enough text because of unnecessary look ahead/behind.
Also optimize and limits valid equals sign expression regexes.
=> fix: issue with expression continuations containing equals

.changeset/fluffy-emus-try.md, src/__tests__/fixtures/tag-var-declaration/__snapshots__/tag-var-declaration.expected.txt, src/__tests__/fixtures/tag-var-declaration/input.marko, src/states/EXPRESSION.ts, src/states/OPEN_TAG.ts
Improves support for adding types to tag variables by treating the tag variable as a continuable expression.
=> feat: tag var type is continuable expression

.changeset/afraid-comics-whisper.md, .changeset/light-trees-laugh.md, .changeset/strange-zoos-tell.md, src/__tests__/fixtures/attr-operators-newline-after/__snapshots__/attr-operators-newline-after.expected.txt, src/__tests__/fixtures/attr-operators-newline-after/input.marko, src/__tests__/fixtures/attr-operators-newline-before/__snapshots__/attr-operators-newline-before.expected.txt, src/__tests__/fixtures/attr-operators-newline-before/input.marko, src/__tests__/fixtures/unary-as-member-expression/__snapshots__/unary-as-member-expression.expected.txt, src/__tests__/fixtures/unary-as-member-expression/input.marko, src/__tests__/main.test.ts, src/states/EXPRESSION.ts, src/states/OPEN_TAG.ts
* When parsing unenclosed expressions we look backwards for unary operators preceded by a word break. This caused a false positive when a member expression was found with the operator name, eg `input.new`. Now we ensure that these operators are not in a member expression like this.
* Improves consistency with v2 of the parser by allowing expressions to span multiple lines if the line is ended with the continuation. This change also allows html attributes and grouped concise attributes to span multiple lines with a new line before _or after_ the continuation.
=> Expression parsing fixes

.changeset/tidy-moles-train.md, package-lock.json, src/__tests__/fixtures/attr-method-shorthand/__snapshots__/attr-method-shorthand.expected.txt, src/__tests__/fixtures/attr-method-shorthand/input.marko, src/__tests__/fixtures/testing/__snapshots__/testing.expected.txt, src/__tests__/fixtures/testing/input.marko, src/states/ATTRIBUTE.ts, src/states/BEGIN_DELIMITED_HTML_BLOCK.ts, src/states/CONCISE_HTML_CONTENT.ts, src/states/INLINE_SCRIPT.ts, src/states/OPEN_TAG.ts, src/states/PLACEHOLDER.ts, src/states/TAG_NAME.ts
For some parser states we expect them to start on the character which they will process. In those cases it typically does a rewind just before entering the state. However a rewind will not work if the parser was already not going to go forward (eg exited a state).
This PR fixes the issue by changing all cases where we rewind to satisfy this to instead force the parser not to go forward.
This fixes an issue where sometime the parser would incorrectly see mismatched brackets.
=> fix: bracket mismatch issue

.changeset/clean-months-cheat.md, src/__tests__/main.test.ts, src/util/util.ts
Switch character position offsets for newlines to be to similar to vscode. Previously the newline was counted as the first character of the line, now it is the last character of the previous line.
=> fix: make character positions for newlines the same as vscode

.changeset/empty-trains-grin.md, .changeset/gold-radios-eat.md, src/__tests__/fixtures/comments-within-open-tag/__snapshots__/comments-within-open-tag.expected.txt, src/__tests__/fixtures/comments-within-open-tag/input.marko, src/__tests__/fixtures/comments-within-tag-body/__snapshots__/comments-within-tag-body.expected.txt, src/__tests__/fixtures/comments-within-tag-body/input.marko, src/states/HTML_CONTENT.ts, src/states/OPEN_TAG.ts
Adds better support for line comments within the open tag, eg:
```marko
<div class="foo" // this class is important
onClick() {} // does stuff
>
```
This PR also makes the slightly breaking change of supporting JS style comments (both `//line` and `/*block*/`) within html content.
This means you can now do:
```marko
<div>
// This is a comment
This is not
</div>
```
Previously you could only use js style comments within concise mode.
=> feat: improve js style comment support

.changeset/gorgeous-laws-grin.md, src/__tests__/fixtures/attr-regexp/__snapshots__/attr-regexp.expected.txt, src/__tests__/fixtures/attr-regexp/input.marko, src/__tests__/fixtures/comments-within-open-tag/__snapshots__/comments-within-open-tag.expected.txt, src/states/EXPRESSION.ts
Fix regression that causes incorrect expression continuations after regexps.
Also causes comments directly after or inside attribute values to be included in the attribute value range.
=> fix: regex continuation issue

.changeset/proud-worms-unite.md, src/core/Parser.ts, src/index.ts, src/util/util.ts
Expose some apis for generating position and location information.
Method to get line offset information:
`getLines(code: string): string`
Method to get a `Position` object given an offset a line offset array (from `getLines`):
`getPosition(lines: number[], offset: number): Position`
Method to get a `Location` object given a start and end offset and a line offset array (from `getLines`):
`getLocation(lines: number[], startOffset: number, endOffset: number): Location`
=> feat: expose position / location / line internal apis

.changeset/wicked-mangos-camp.md, src/__tests__/fixtures/comments-within-tag-body/__snapshots__/comments-within-tag-body.expected.txt, src/__tests__/fixtures/comments-within-tag-body/input.marko, src/states/HTML_CONTENT.ts
Fix regression around JS style comments in the body by requiring that they are preceded by a whitespace.
This was caused by #119 which noted that this was potentially a breaking change. We didn't for see a common edge case however which was http links inside some content, eg:
```marko
<a href="http://ebay.com">
http://ebay.com
</a>
```
With #119 that caused the code above to treat `//ebay.com` as a JS comment which was not desirable.
Now by requiring a whitespace (eg a newline) before any JS style comments within the html content we avoid this common gotcha while maintaining support for this syntax/feature.
=> fix: require a whitespace before js style comments inside html content

.changeset/neat-cobras-battle.md, .changeset/quick-seals-watch.md, src/__tests__/fixtures/cdata/__snapshots__/cdata.expected.txt, src/__tests__/fixtures/cdata/input.marko, src/__tests__/fixtures/script-single-line-comment/__snapshots__/script-single-line-comment.expected.txt, src/__tests__/fixtures/script-single-line-comment/input.marko, src/states/JS_COMMENT_LINE.ts, src/states/PARSED_TEXT_CONTENT.ts
Fixes an issue where parsed text state tags (eg `<script>`) were not properly being ended if the line ended with a comment.
This was a regression.
```
<script>// This should close even though there is a line comment on the same line</script>
```
=> fix: regression with comments inside parsed text state

.changeset/blue-phones-agree.md, src/core/Parser.ts
Small parser performance improvement by optimizing the base parser constructor to not initialize undefined properties.
=> perf: optimize parser constructor

.changeset/mean-buses-mate.md, src/__tests__/fixtures/attr-method-shorthand/__snapshots__/attr-method-shorthand.expected.txt, src/__tests__/fixtures/attr-method-shorthand/input.marko, src/__tests__/fixtures/attr-operators-space-between/__snapshots__/attr-operators-space-between.expected.txt, src/__tests__/fixtures/attr-operators-space-between/input.marko, src/states/EXPRESSION.ts
Fixes a parse error where division is immediately followed by enclosed code.
Specifically if an expression looked something like
```js
x / (y[z])
```
When the parser encountered division it consumed the whitespace and went one character ahead. In the above example that'd cause it to skip over the `(` which caused the enclosed expression tracking to be off.
=> fix: issue with parsing division followed by encloused code

.changeset/beige-seahorses-talk.md, src/__tests__/fixtures/attr-complex-instanceof/__snapshots__/attr-complex-instanceof.expected.txt, src/__tests__/fixtures/attr-complex-instanceof/input.marko, src/states/EXPRESSION.ts
Fixes an issue where attribute names that started with a keyword (eg: `as-thing` or `instanceof-thing`) were incorrectly treated as an expression continuation.
=> fix: ensure keyword operators are always followed by a space

.changeset/lovely-chefs-pump.md, src/__tests__/fixtures/tag-var-before-concise-text/__snapshots__/tag-var-before-concise-text.expected.txt, src/__tests__/fixtures/tag-var-before-concise-text/input.marko, src/__tests__/main.test.ts, src/states/OPEN_TAG.ts
The following would cause the parser to see the `-` after the tag var as an expression continuation instead of beginning a concise text block.
```marko
style/style --
header {
color: green
}
```
=> fix: tag variable not terminated on concise mode text delimiter

.changeset/bright-clouds-yawn.md, .changeset/four-boxes-brush.md, .changeset/nice-cats-relate.md, src/__tests__/fixtures/coma-after-open-tag/__snapshots__/coma-after-open-tag.expected.txt, src/__tests__/fixtures/coma-after-open-tag/input.marko, src/__tests__/fixtures/scriptlet-eof/__snapshots__/scriptlet-eof.expected.txt, src/__tests__/fixtures/scriptlet-eof/input.marko, src/core/Parser.ts, src/states/EXPRESSION.ts, src/states/OPEN_TAG.ts, src/states/TAG_NAME.ts
* Expression continuations after a period will now only happen if the period is followed by something that could be an identifier (eg a word).
* Comas after the tag name will now always enter into attribute parsing mode.
* When in concise mode, a new line that starts with a coma will now continue the attributes for the previous tag.
=> Avoid period continuation for non identifier, improve coma sep handling for attrs

.changeset/stale-impalas-visit.md, src/__tests__/fixtures/attr-complex-unary/__snapshots__/attr-complex-unary.expected.txt, src/__tests__/fixtures/attr-complex-unary/input.marko, src/states/EXPRESSION.ts
Fix regression where the parser would continue unary keyword expressions even if the keyword was inside a word boundary. Eg `<div class=thing_new x>` would cause the parser to see the expression as `thing_` and `new x`.
=> fix: ensure unary expression continuation is a word boundary

.changeset/eight-shirts-dream.md, src/__tests__/fixtures/script-with-strings/__snapshots__/script-with-strings.expected.txt, src/__tests__/fixtures/script-with-strings/input.marko, src/states/PARSED_STRING.ts, src/states/PARSED_TEXT_CONTENT.ts, src/states/index.ts
Fixes an regression where string literals inside of parsed text nodes (eg `<script>`) were not properly changing the parser state. This caused issues when comment like syntax was embedded within these string literals"
=> fix: parsed text string literals

.changeset/tall-moons-enjoy.md, src/__tests__/fixtures/attr-complex-unary/__snapshots__/attr-complex-unary.expected.txt, src/__tests__/fixtures/attr-complex-unary/input.marko, src/__tests__/fixtures/tag-var-type-with-parens/__snapshots__/tag-var-type-with-parens.expected.txt, src/__tests__/fixtures/tag-var-type-with-parens/input.marko, src/states/EXPRESSION.ts
Ensures that in the expression state whenever a terminator is found for the expression and the terminator is preceded by an operator that expression state continues.
This allows for better parsing of expressions in several places. The case that brought about this change was as follows:
```
<let/a:(B | C) = D/>
```
With the above the tag variable state was being terminated by the `(` and going into tag arguments / shorthand default method mode. With this change it will now see the paren and walk backward past whitespace to see the `:` which is an expression operator causing the `(B | C)` to be a part of the tag variable (for types).
=> fix: always consume terminator if it is preceded by an operator

.changeset/heavy-stingrays-invite.md, src/__tests__/fixtures/css-grid/__snapshots__/css-grid.expected.txt, src/__tests__/fixtures/css-grid/input.marko, src/states/EXPRESSION.ts
Improves the detection of division vs regexp expressions to assume division when the preceding character is a quote.
This improves parsing of css grid properties in particular.
Note in the future this could probably be improved to remove the regexp state altogether for non script sections, but that would require a larger refactor.
=> fix: improve detection of regexp vs division

.changeset/floppy-shirts-beg.md, package-lock.json, src/__tests__/fixtures/commas-relax/__snapshots__/commas-relax.expected.txt, src/__tests__/fixtures/commas-relax/input.marko, src/core/Parser.ts, src/states/EXPRESSION.ts, src/states/OPEN_TAG.ts, src/states/TAG_NAME.ts, src/util/util.ts
Previously a parse error was thrown when a statement (eg `import`, `export`) had indented content.
Now instead of throwing an error the parser will continue while indented for these statements.
Resolves https://github.com/marko-js/prettier/issues/55
=> fix: allow indented content within statement tags

.changeset/chubby-glasses-read.md, src/__tests__/fixtures/ts-static-const-arrow-function-return-type/__snapshots__/ts-static-const-arrow-function-return-type.expected.txt, src/__tests__/fixtures/ts-static-const-arrow-function-return-type/input.marko, src/states/EXPRESSION.ts
=> fix: arrow functions content was being parsed as types
